### ISSUE TITLE
Add The Wizard of Oz movie

### ISSUE THREAD

**Issue by mikeleguedes** [mikeleguedes/json-movie-list#110]

**Comment by alexxmitchell** [comment]
I'd like to work on this

**Comment by JeffResc** [comment]
Please assign this issue to me, I'd be interested in working on it.
Thanks.

**Comment by mikeleguedes** [comment]
> Please assign this issue to me, I'd be interested in working on it.
> Thanks.

Sorry dear, I already did it, but I will open more issues to work on it
