### ISSUE TITLE
Add King Kong  movie

### ISSUE THREAD

**Issue by mikeleguedes** [mikeleguedes/json-movie-list#113]
1933

**Comment by Apoorv-Gaurav-Agarwal** [comment]
hello, please assign this to me

**Comment by Apoorv-Gaurav-Agarwal** [comment]
The one I added was 2005 version of this movie

**Comment by mikeleguedes** [comment]
> The one I added was 2005 version of this movie

This issue is to 1933. I will add a issue to 2005
