### ISSUE TITLE
Add Avengers: Infinity War movie

### ISSUE THREAD

**Issue by mikeleguedes** [mikeleguedes/json-movie-list#54]

**Comment by gchagan36** [comment]
I'll do this one

**Comment by Apoorv-Gaurav-Agarwal** [comment]
If something is still available, I would like to help.

**Comment by mikeleguedes** [comment]
> If something is still available, I would like to help.

I will add more movies soon @Apoorv-Gaurav-Agarwal  😄

**Comment by Apoorv-Gaurav-Agarwal** [comment]
Sure :)

**Comment by mikeleguedes** [comment]
> I'll do this one

Do you did the PR? 🤔

**Comment by gchagan36** [comment]
> > I'll do this one
> 
> Do you did the PR? 🤔

Feature/avengers infinity war #62
