### ISSUE TITLE
Adding movie to already existing years?

### ISSUE THREAD

**Issue by mattwright42** [mikeleguedes/json-movie-list#84]
Are we able to add more movies to years that already exist?

When a movie is added, are we meant to update the other files as well (actors and directors)?

Would love to add some more classic movies to years that only have one or two movies...thanks!

**Comment by mikeleguedes** [comment]
Yes, sure! I love the classics ✨ 😍
I'm going to open issues to this, but be free to add those wonderful classic movies 😄

**Comment by mikeleguedes** [comment]
I will add you in the contributors so you be able to open issues, okay? @mattwright42

**Comment by mattwright42** [comment]
Awesome. Thank you!
