### ISSUE TITLE
Help to review the pr's

### ISSUE THREAD

**Issue by mikeleguedes** [mikeleguedes/json-movie-list#95]
I need some people to help me with the PR's 'cause I don't have much free time to do this. 

*Free time to:
*Open issues
*Approve PR's
*Know de rules and run the test
*Be kind with others 😸 
*Is necessary to be responsible and commitment

**Comment by kwaimind** [comment]
🙋‍♂️I can help

**Comment by leonlafa** [comment]
Happy to help

**Comment by kwaimind** [comment]
Thanks @mikeleguedes 

Are you happy for us to merge pull requests too?

**Comment by mattwright42** [comment]
I'm planning on helping as well. :)

**Comment by kwaimind** [comment]
Running into some errors with special characters in titles (i.e. ":" or "é") when running tests.

Can we add support for those?

./movies/2019/marvel-avengers-endgame.json movie name is either wrong or file name is not according to guidelines. Expected: avengers-endgame.json
./movies/2019/pokemon-detective-pikachu.json movie name is either wrong or file name is not according to guidelines. Expected: pokémon-detective-pikachu.json

**Comment by mikeleguedes** [comment]
@kwaimind 

> Running into some errors with special characters in titles (i.e. ":" or "é") when running tests.
> 
> Can we add support for those?
> 
> ./movies/2019/marvel-avengers-endgame.json movie name is either wrong or file name is not according to guidelines. Expected: avengers-endgame.json
> ./movies/2019/pokemon-detective-pikachu.json movie name is either wrong or file name is not according to guidelines. Expected: pokémon-detective-pikachu.json

Sure! 😄

**Comment by leonlafa** [comment]
@mikeleguedes how do you feel about me creating an issue workflow?  

I have noticed that there isn't a standardised process for creating new issues. e.g features,  bugs, questions etc. 

I'm more than happy to implement this, let me know your thoughts 😄

**Comment by jorgeruvalcaba** [comment]
I would like to help
